{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "from torch.autograd import Variable\n",
    "import torchvision\n",
    "from torch.nn import init\n",
    "\n",
    "from torchvision.models.resnet import BasicBlock, ResNet\n",
    "from torchvision.transforms import ToTensor\n",
    "from scipy.io import savemat,loadmat\n",
    "\n",
    "import io\n",
    "from torchvision import models, transforms\n",
    "import torch.utils.data as data_utils\n",
    "from PIL import Image\n",
    "import os\n",
    "\n",
    "import cv2\n",
    "import matplotlib.pyplot as plt\n",
    "import torch.nn.functional as F\n",
    "def default_loader(path):\n",
    "    return Image.open(path)   "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from torchvision.models.resnet import BasicBlock, ResNet\n",
    "from torch.nn import init\n",
    "\n",
    "def conv(in_planes, out_planes, kernel_size=3, stride=1, dilation=1, bias=False, transposed=False):\n",
    "    if transposed:\n",
    "        layer = nn.ConvTranspose2d(in_planes, out_planes, kernel_size=kernel_size, stride=stride, padding=1, output_padding=1,\n",
    "                                   dilation=dilation, bias=bias)\n",
    "    else:\n",
    "        padding = (kernel_size + 2 * (dilation - 1)) // 2\n",
    "        layer = nn.Conv2d(in_planes, out_planes, kernel_size=kernel_size, stride=stride, padding=padding, dilation=dilation, bias=bias)\n",
    "    if bias:\n",
    "        init.constant(layer.bias, 0)\n",
    "    return layer\n",
    "\n",
    "# Returns 2D batch normalisation layer\n",
    "def bn(planes):\n",
    "    layer = nn.BatchNorm2d(planes)\n",
    "    # Use mean 0, standard deviation 1 init\n",
    "    init.constant(layer.weight, 1)\n",
    "    init.constant(layer.bias, 0)\n",
    "    return layer\n",
    "\n",
    "\n",
    "class FeatureResNet(ResNet):\n",
    "    def __init__(self):\n",
    "        super().__init__(BasicBlock, [3, 14, 16, 3], 1000)\n",
    "        self.conv_f = conv(2,64, kernel_size=3,stride = 1)\n",
    "        self.ReLu_1 = nn.ReLU(inplace=True)\n",
    "        self.conv_pre = conv(512, 1024, stride=2, transposed=False)\n",
    "        self.bn_pre = bn(1024)\n",
    "\n",
    "    def forward(self, x):\n",
    "        x1 = self.conv_f(x)\n",
    "        #print('x1',x1.size())\n",
    "        x = self.bn1(x1)\n",
    "        #print(x.size())\n",
    "        x = self.relu(x)\n",
    "        #print(x.size())\n",
    "        x2 = self.maxpool(x)\n",
    "        #print('x2',x2.size())\n",
    "        x = self.layer1(x2)\n",
    "        #print(x2.size())\n",
    "        x3 = self.layer2(x)\n",
    "        #print('x3',x3.size())\n",
    "        x4 = self.layer3(x3)\n",
    "        #print('x4',x4.size())\n",
    "        x5 = self.layer4(x4)\n",
    "        #print('x5',x5.size())\n",
    "        x6 = self.ReLu_1(self.bn_pre(self.conv_pre(x5)))\n",
    "        #print('x6',x6.size())\n",
    "        return x1, x2, x3, x4, x5,x6\n",
    "\n",
    "\n",
    "class SegResNet(nn.Module):\n",
    "    def __init__(self, num_classes, pretrained_net):\n",
    "        super().__init__()\n",
    "        self.pretrained_net = pretrained_net\n",
    "        self.relu = nn.ReLU(inplace=True)\n",
    "        #self.conv3 = conv(1024,1024, stride=1, transposed=False)\n",
    "        #self.bn3 = bn(1024)\n",
    "        self.conv3_2 = conv(1024, 512, stride=1, transposed=False)\n",
    "        self.bn3_2 = bn(512)\n",
    "        self.conv4 = conv(512,512, stride=2, transposed=True)\n",
    "        self.bn4 = bn(512)\n",
    "        self.conv5 = conv(512, 256, stride=2, transposed=True)\n",
    "        self.bn5 = bn(256)\n",
    "        self.conv6 = conv(256, 128, stride=2, transposed=True)\n",
    "        self.bn6 = bn(128)\n",
    "        self.conv7 = conv(128, 64, stride=2, transposed=True)\n",
    "        self.bn7 = bn(64)\n",
    "        self.conv8 = conv(64, 64, stride=2, transposed=True)\n",
    "        self.bn8 = bn(64)\n",
    "        self.conv9 = conv(64, 32, stride=1, transposed=False)\n",
    "        self.bn9 = bn(32)\n",
    "        self.convadd = conv(32, 16, stride=1, transposed=False)\n",
    "        self.bnadd = bn(16)\n",
    "        self.conv10 = conv(16, num_classes,stride=2, kernel_size=3)\n",
    "        init.constant(self.conv10.weight, 0)  # Zero init\n",
    "\n",
    "    def forward(self, x):\n",
    "        #b,c,w,h = x.size()\n",
    "        #x = x.view(b,c,w,h)\n",
    "        x1, x2, x3, x4, x5, x6 = self.pretrained_net(x)\n",
    "        #x1 = x1.view(b,x1.size(1),x1.size(2),x1.size(3))\n",
    "        #x2 = x2.view(b,x2.size(1),x2.size(2),x2.size(3))\n",
    "        #x3 = x3.view(b,x3.size(1),x3.size(2),x3.size(3))\n",
    "        #x4 = x4.view(b,x4.size(1),x4.size(2),x4.size(3))\n",
    "        #x5 = x5.view(b,x5.size(1),x5.size(2),x5.size(3))\n",
    "\n",
    "        #x1 = torch.max(x1,1)[0]\n",
    "        #x2 = torch.max(x2,1)[0]\n",
    "        #x3 = torch.max(x3,1)[0]\n",
    "        #x4 = torch.max(x4,1)[0]\n",
    "        #x5 = torch.max(x5,1)[0]\n",
    "\n",
    "\n",
    "        #print(x5.size())\n",
    "        #print(x4.size())\n",
    "        #print(x1.size())\n",
    "        #x = self.relu(self.bn3(self.conv3(x6)))\n",
    "        x = self.relu(self.bn3_2(self.conv3_2(x6)))\n",
    "        \n",
    "        x = self.relu(self.bn4(self.conv4(x)))\n",
    "        x = self.relu(self.bn5(self.conv5(x)))\n",
    "        #print(x.size())\n",
    "        x = self.relu(self.bn6(self.conv6(x+x4 )))\n",
    "        #print(x.size())\n",
    "        x = self.relu(self.bn7(self.conv7(x+x3 )))\n",
    "        #print(x.size())\n",
    "        x = self.relu(self.bn8(self.conv8(x+x2 )))\n",
    "        #print(x.size())\n",
    "        x = self.relu(self.bn9(self.conv9(x+x1 )))\n",
    "        #print(x.size())\n",
    "        x = self.relu(self.bnadd(self.convadd(x)))\n",
    "        x = self.conv10(x)\n",
    "        return x\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "fnet = FeatureResNet()\n",
    "fcn = SegResNet(4,fnet)\n",
    "fcn = fcn.cuda()\n",
    "fcn.load_state_dict(torch.load('PATH_TO_PRETRAINED' + 'pretrained_strainnet'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "displacement_result_path = ''\n",
    "speckle_img_path = ''\n",
    "result_path = ''\n",
    "\n",
    "for i in range(1,num_img):\n",
    "    f = loadmat(displacement_result_path+'/result_'+str(i)+'position.mat')  #load ROI\n",
    "    [x1,x2,y1,y2] = f['position'][0,0:4]\n",
    "    \n",
    "    h0 = int((x2-x1))\n",
    "    w0 = int((y2-y1))\n",
    "    hnew = int((h0//32+1)*32)\n",
    "    wnew = int((w0//32+1)*32)\n",
    "    newsize = (wnew,hnew)\n",
    "    \n",
    "    \n",
    "    img1 = default_loader('first_img')\n",
    "    img1_c = img1.crop((y1,x1,y2,x2))\n",
    "    img1_r = img1_c.resize(newsize)\n",
    "    img2 = default_loader('second_img')\n",
    "    img2_c = img2.crop((y1,x1,y2,x2))\n",
    "    img2_r = img2_c.resize(newsize)\n",
    "    \n",
    "    img_1 = ToTensor()(img1_r)\n",
    "    img_2 = ToTensor()(img2_r)\n",
    "    imgs2 = torch.cat((img_1/np.max(img_1.numpy()), img_2/np.max(img_1.numpy())), 0)\n",
    "    imgs2 = imgs.unsqueeze(0)\n",
    "    imgs2 = imgs.type(torch.cuda.FloatTensor)\n",
    "    imgs2 = Variable(imgs).cuda()\n",
    "    \n",
    "    predict = fcn(imgs)\n",
    "    predict_np = predict.detach().cpu().numpy().squeeze(0)\n",
    "    \n",
    "    \n",
    "    strain = predict_np*0.01\n",
    "\n",
    "    \n",
    "    matname = result_path+str(i)+'strain.mat'\n",
    "    mdic = {\"strain\": strain, \"label\": \"strain\"}\n",
    "    savemat(matname,mdic)\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
